apiVersion: v1
kind: Service
metadata:
  name: daskd-scheduler
  labels:
    app: daskd
    role: scheduler
spec:
  ports:
  - port: 8786
    targetPort: 8786
    name: scheduler
  - port: 8787
    targetPort: 8787
    name: bokeh
  - port: 9786
    targetPort: 9786
    name: http
  selector:
    app: daskd
    role: scheduler
  type: LoadBalancer
--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: daskd-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daskd
        role: scheduler
    spec:
      containers:
      - name: scheduler
        image: hammerlab/mhcflurry-misc:dev1
        imagePullPolicy: Always
        command: ["venv-py3/bin/dask-scheduler"]
        resources:
          requests:
            cpu: 10
            # memory: 5000Mi
        ports:
        - containerPort: 8786
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: daskd-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daskd
        role: worker
    spec:
      containers:
      - name: worker
        image: hammerlab/mhcflurry-misc:dev1
        imagePullPolicy: Always
        command: [
          "/bin/bash",
          "-cx",
          "env && venv-py3/bin/dask-worker $DASKD_SCHEDULER_SERVICE_HOST:$DASKD_SCHEDULER_SERVICE_PORT_SCHEDULER --nthreads 1",
        ]
        resources:
          requests:
            cpu: 10
            # memory: 2000Mi

